Repository nspcc-dev/neofs-api-go, pull requests merged in 2021-06, with the labels that each got.

#290 Feature/Add `WithURIAddress` option
  pkg/client/opts.go
  rpc/client/options.go
  rpc/client/options_test.go
Labels: enhancement

#301 Feature/add `MarshalHeaderJSON` method
  pkg/object/object.go
Labels: enhancement

#305 docs/Add release instructions
  docs/release-instruction.md
Labels: documentation

#308 grpc: Fix the format of full method names
  rpc/grpc/util.go
Labels: bug

#314 client/object: Add payload-handling parameter to GetObjectParams
  pkg/client/object.go
Labels: enhancement

#316 Fix object stream-based io.Reader
  pkg/client/object.go
  pkg/client/object_test.go
Labels: bug

#312 netmap: Support multiple addresses in NodeInfo
  pkg/netmap/node_info.go
  pkg/netmap/node_info_test.go
  pkg/netmap/test/generate.go
  v2/netmap/convert.go
  v2/netmap/grpc/types.go
  v2/netmap/grpc/types.pb.go
  v2/netmap/marshal.go
  v2/netmap/test/generate.go
  v2/netmap/types.go
Labels: enhancement

#318 Implement crypto libs and remove neofs-crypto usage
  .github/workflows/go.yml
  crypto/algo/algo.go
  crypto/algo/doc.go
  crypto/algo/keys.go
  crypto/doc.go
  crypto/ecdsa/doc.go
  crypto/ecdsa/ecdsa.go
  crypto/ecdsa/ecdsa_test.go
  crypto/ecdsa/test/signer.go
  crypto/proto/doc.go
  crypto/proto/sign.go
  crypto/rfc6979/doc.go
  crypto/rfc6979/rfc6979.go
  crypto/rfc6979/rfc6979_test.go
  crypto/rfc6979/test/signer.go
  crypto/sign.go
  crypto/signer.go
  crypto/test/doc.go
  crypto/test/signer.go
  crypto/util/doc.go
  crypto/util/pool.go
  go.mod
  go.sum
  pkg/acl/eacl/record.go
  pkg/acl/eacl/record_test.go
  pkg/acl/eacl/target.go
  pkg/acl/eacl/target_test.go
  pkg/client/accounting.go
  pkg/client/container.go
  pkg/client/netmap.go
  pkg/client/object.go
  pkg/client/object_test.go
  pkg/client/opts.go
  pkg/client/reputation.go
  pkg/client/session.go
  pkg/object/fmt.go
  pkg/object/fmt_test.go
  pkg/owner/id_test.go
  pkg/owner/wallet.go
  pkg/reputation/peer.go
  pkg/reputation/test/generate.go
  pkg/reputation/trust.go
  pkg/session/session.go
  pkg/session/test/token.go
  pkg/token/bearer.go
  pkg/token/bearer_test.go
  pkg/token/test/generate.go
  util/signature/data.go
  util/signature/options.go
  util/signature/util.go
  v2/crypto/doc.go
  v2/crypto/sign.go
  v2/signature/sign.go
  v2/signature/sign_test.go
Labels: enhancement
